version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  Etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-tier

  Mysql:
    image: 'bitnami/mysql:latest'
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /Users/tdd/docker/mysql/log:/var/log/mysql
      - /Users/tdd/docker/mysql/data:/var/lib/mysql
      - /Users/tdd/docker/mysql/conf.d:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 20s
      retries: 10
    restart: always
    networks:
      - app-tier

  Redis:
    image: 'redis:latest'
    container_name: redis
    volumes:
      - /Users/tdd/docker/redis/data:/data
      - /Users/tdd/docker/redis/redis.conf:/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime:ro
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-tier

  Prometheus:
    image: 'prom/prometheus:latest'
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/tdd/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-tier

  Grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - '3000:3000'
    networks:
      - app-tier

  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"
    restart: always
    networks:
      - app-tier

  app:
    build:
      context: .
      dockerfile: ops/Dockerfile
    container_name: app_gin_user
    restart: always
    environment:
      - GIN_MODE=release
      - TZ=Asia/Shanghai
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      Mysql:
        condition: service_healthy
      Redis:
        condition: service_healthy
      jaeger:
        condition: service_started
    ports:
      - "5001:5001"
    networks:
      - app-tier
